osx_image: xcode8.3
language: swift
before_install:
- brew update
- brew install carthage || brew upgrade carthage
script:
- set -o pipefail && carthage bootstrap && xcodebuild build -project MastodonSwift.xcodeproj -scheme MastodonSwift-iOS -sdk iphonesimulator10.3 ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' | xcpretty
