name: Run tests

on:
  workflow_dispatch:
  pull_request:
  push:
    - main

jobs:
  run_tests:
    name: Run Tests
    runs-on: macos-12
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Select required Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_14.1.app
      - name: Run tests
        run: swift test
